#!/bin/sh

./k5-dstatus &

sleep 1s

dbus-send --print-reply --session --dest=com.astro73.k5dstatus --type=method_call /com/astro73/k5dstatus \
        com.astro73.k5dstatus.Manager.CreateBlock string:'spam' dict:string:string:full_text,'Spam!'
dbus-send --print-reply --session --dest=com.astro73.k5dstatus --type=method_call /com/astro73/k5dstatus \
        com.astro73.k5dstatus.Manager.CreateBlock string:'eggs' dict:string:string:full_text,'Eggs!'

wait %1