#!/bin/sh

./k5-dstatus &

sleep 1s

dbus-send --print-reply --session --dest=com.astro73.k5dstatus --type=method_call /com/astro73/k5dstatus \
        com.astro73.k5dstatus.Manager.CreateBlock dict:string:string:full_text,'Spam!',name,'spam'
dbus-send --print-reply --session --dest=com.astro73.k5dstatus --type=method_call /com/astro73/k5dstatus \
        com.astro73.k5dstatus.Manager.CreateBlock dict:string:string:full_text,'Eggs!',name,'eggs'

wait %1