#!/usr/bin/env python3
import time
from k5dstatus.utils import get_config, make_block

config = get_config('clock')

time_format = config.get('format', '%m/%d <b>%H:%M</b>')

last_time = ''

with make_block(
    name="clock",
    markup="pango",
) as bgen:
    block = bgen()

    while True:
        time_string = time.strftime(time_format)
        if time_string != last_time:
            last_time = time_string
            block["full_text"] = time_string
        time.sleep(1)
